### ISSUE TITLE
Console fails to render my template

### ISSUE THREAD

**Issue by vpavlin** [akash-network/console#135]
When I try to deploy a Waku node

https://deploy.cloudmos.io/new-deployment?step=edit-deployment&templateId=akash-network-awesome-akash-waku

and switch to `Builder` tab, the webapp fails with the following error:

```
Error
Cannot read properties of undefined (reading 'forEach')
```

Developer Console shows following error:

```
_app-26ad16ad536a0b56.js:223 TypeError: Cannot read properties of undefined (reading 'forEach')
    at o (8849-0244ab259002c6a2.js?__WB_REVISION__=0244ab259002c6a2:1:50150)
    at new-deployment-b787575f1d4bf7b9.js?__WB_REVISION__=b787575f1d4bf7b9:1:15393
    at Object.next (_app-26ad16ad536a0b56.js:272:101912)
    at Object.ed [as next] (_app-26ad16ad536a0b56.js:272:92681)
    at _app-26ad16ad536a0b56.js:272:91924
    at uU (framework-2645a99191cfc5e9.js:9:84120)
    at oV (framework-2645a99191cfc5e9.js:9:113178)
    at o (framework-2645a99191cfc5e9.js:9:107731)
    at x (framework-2645a99191cfc5e9.js:33:1364)
    at MessagePort.T (framework-2645a99191cfc5e9.js:33:1894)
 ```

**Comment by baktun14** [comment]
Thanks for reporting. So the template is breaking because it doesn't have ephemeral storage. I will push a fix for the sdl builder soon.

Ref: https://github.com/akash-network/support/issues/203

**Comment by vpavlin** [comment]
Seems to work fine now! Thanks!
