### ISSUE TITLE
console UI is breaking with error `Cannot read properties of undefined (reading 'amount')`

### ISSUE THREAD

**Issue by aleem1314** [akash-network/console#387]
## Summary

Since yesterday console UI not working. Website is crashing with following error.

Browser error
```
Application error: a client-side exception has occurred (see the browser console for more information).
```

Console error
```
_app-d9f79765a1e761c1.js:153 TypeError: Cannot read properties of undefined (reading 'amount')
    at _app-d9f79765a1e761c1.js:136:3418544
    at Array.reduce (<anonymous>)
    at _app-d9f79765a1e761c1.js:136:3418498
    at uU (framework-48b742837832a3b5.js:9:84107)
    at oA (framework-48b742837832a3b5.js:9:113154)
    at oP (framework-48b742837832a3b5.js:9:95973)
    at r8 (framework-48b742837832a3b5.js:9:44812)
    at framework-48b742837832a3b5.js:9:111601
    at oU (framework-48b742837832a3b5.js:9:111607)
    at oE (framework-48b742837832a3b5.js:9:94976)
    at E (framework-48b742837832a3b5.js:33:1364)
    at MessagePort.T (framework-48b742837832a3b5.js:33:1894)
```

I even cleared browser cache, still same error.

**Comment by baktun14** [comment]
Hi, on which page are you getting this error?

**Comment by aleem1314** [comment]
Getting this error on every page. This is only happening if you have active deployments.

**Comment by baktun14** [comment]
@aleem1314 Can you share your address please? I'm baktun14 on discord if you want to dm it

**Comment by baktun14** [comment]
Is this still an issue? @aleem1314

**Comment by aleem1314** [comment]
Yes, still same issue.
You can test it with this account akash16d78ez8ec3md9vsrqjywmjzqm8wd69nzmqwvln

**Comment by baktun14** [comment]
It should be fixed now, lmk if it's still not working.
