### ISSUE TITLE
Problem Running Console Application Locally

### ISSUE THREAD

**Issue by asayadi** [akash-network/console#513]
I am trying to run the Console app locally so that I can develop on it. After following the instructions of:

git clone git@github.com:akash-network/console.git ./akash-console
cd akash-console
npm run dc:up:dev -- deploy-web

I see errors such as the following:

Failed to validate server environment variables ZodError: [
deploy-web-1        |   {
deploy-web-1        |     "code": "invalid_type",
deploy-web-1        |     "expected": "string",
deploy-web-1        |     "received": "undefined",
deploy-web-1        |     "path": [
deploy-web-1        |       "NEXT_PUBLIC_MASTER_WALLET_ADDRESS"
deploy-web-1        |     ],
deploy-web-1        |     "message": "Required"
deploy-web-1        |   },
deploy-web-1        |   {
deploy-web-1        |     "code": "invalid_type",
deploy-web-1        |     "expected": "string",
deploy-web-1        |     "received": "undefined",
deploy-web-1        |     "path": [
deploy-web-1        |       "NEXT_PUBLIC_UAKT_TOP_UP_MASTER_WALLET_ADDRESS"
deploy-web-1        |     ],
deploy-web-1        |     "message": "Required"
deploy-web-1        |   },
deploy-web-1        |   {
deploy-web-1        |     "code": "invalid_type",
deploy-web-1        |     "expected": "string",
deploy-web-1        |     "received": "undefined",
deploy-web-1        |     "path": [
deploy-web-1        |       "NEXT_PUBLIC_USDC_TOP_UP_MASTER_WALLET_ADDRESS"
deploy-web-1        |     ],
deploy-web-1        |     "message": "Required"
deploy-web-1        |   },
deploy-web-1        |   {
deploy-web-1        |     "code": "invalid_type",
deploy-web-1        |     "expected": "string",
deploy-web-1        |     "received": "undefined",
deploy-web-1        |     "path": [
deploy-web-1        |       "NEXT_PUBLIC_API_BASE_URL"
deploy-web-1        |     ],
deploy-web-1        |     "message": "Required"
deploy-web-1        |   },
deploy-web-1        |   {
deploy-web-1        |     "code": "invalid_type",
deploy-web-1        |     "expected": "string",
deploy-web-1        |     "received": "undefined",
deploy-web-1        |     "path": [
deploy-web-1        |       "NEXT_PUBLIC_STATS_APP_URL"
deploy-web-1        |     ],
deploy-web-1        |     "message": "Required"
deploy-web-1        |   },
deploy-web-1        |   {
deploy-web-1        |     "code": "invalid_type",
deploy-web-1        |     "expected": "string",
deploy-web-1        |     "received": "undefined",
deploy-web-1        |     "path": [
deploy-web-1        |       "NEXT_PUBLIC_PROVIDER_PROXY_URL"
deploy-web-1        |     ],
deploy-web-1        |     "message": "Required"
deploy-web-1        |   },
deploy-web-1        |   {
deploy-web-1        |     "code": "invalid_type",
deploy-web-1        |     "expected": "string",
deploy-web-1        |     "received": "undefined",
deploy-web-1        |     "path": [
deploy-web-1        |       "NEXT_PUBLIC_PROVIDER_PROXY_URL_WS"
deploy-web-1        |     ],
deploy-web-1        |     "message": "Required"
deploy-web-1        |   },
deploy-web-1        |   {
deploy-web-1        |     "code": "invalid_type",
deploy-web-1        |     "expected": "string",
deploy-web-1        |     "received": "undefined",
deploy-web-1        |     "path": [
deploy-web-1        |       "NEXT_PUBLIC_BASE_API_MAINNET_URL"
deploy-web-1        |     ],
deploy-web-1        |     "message": "Required"
deploy-web-1        |   },
deploy-web-1        |   {
deploy-web-1        |     "code": "invalid_type",
deploy-web-1        |     "expected": "string",
deploy-web-1        |     "received": "undefined",
deploy-web-1        |     "path": [
deploy-web-1        |       "NEXT_PUBLIC_BASE_API_TESTNET_URL"
deploy-web-1        |     ],
deploy-web-1        |     "message": "Required"
deploy-web-1        |   },
deploy-web-1        |   {
deploy-web-1        |     "code": "invalid_type",
deploy-web-1        |     "expected": "string",
deploy-web-1        |     "received": "undefined",
deploy-web-1        |     "path": [
deploy-web-1        |       "NEXT_PUBLIC_BASE_API_SANDBOX_URL"
deploy-web-1        |     ],
deploy-web-1        |     "message": "Required"
deploy-web-1        |   },
deploy-web-1        |   {
deploy-web-1        |     "code": "invalid_type",
deploy-web-1        |     "expected": "string",
deploy-web-1        |     "received": "undefined",
deploy-web-1        |     "path": [
deploy-web-1        |       "AUTH0_SECRET"
deploy-web-1        |     ],
deploy-web-1        |     "message": "Required"
deploy-web-1        |   },
deploy-web-1        |   {
deploy-web-1        |     "code": "invalid_type",
deploy-web-1        |     "expected": "string",
deploy-web-1        |     "received": "undefined",
deploy-web-1        |     "path": [
deploy-web-1        |       "AUTH0_BASE_URL"
deploy-web-1        |     ],
deploy-web-1        |     "message": "Required"
deploy-web-1        |   },
deploy-web-1        |   {
deploy-web-1        |     "code": "invalid_type",
deploy-web-1        |     "expected": "string",
deploy-web-1        |     "received": "undefined",
deploy-web-1        |     "path": [
deploy-web-1        |       "AUTH0_ISSUER_BASE_URL"
deploy-web-1        |     ],
deploy-web-1        |     "message": "Required"
deploy-web-1        |   },
deploy-web-1        |   {
deploy-web-1        |     "code": "invalid_type",
deploy-web-1        |     "expected": "string",
deploy-web-1        |     "received": "undefined",
deploy-web-1        |     "path": [
deploy-web-1        |       "AUTH0_CLIENT_ID"
deploy-web-1        |     ],
deploy-web-1        |     "message": "Required"
deploy-web-1        |   },
deploy-web-1        |   {
deploy-web-1        |     "code": "invalid_type",
deploy-web-1        |     "expected": "string",
deploy-web-1        |     "received": "undefined",
deploy-web-1        |     "path": [
deploy-web-1        |       "AUTH0_CLIENT_SECRET"
deploy-web-1        |     ],
deploy-web-1        |     "message": "Required"
deploy-web-1        |   },
deploy-web-1        |   {
deploy-web-1        |     "code": "invalid_type",
deploy-web-1        |     "expected": "string",
deploy-web-1        |     "received": "undefined",
deploy-web-1        |     "path": [
deploy-web-1        |       "BASE_API_TESTNET_URL"
deploy-web-1        |     ],
deploy-web-1        |     "message": "Required"
deploy-web-1        |   },
deploy-web-1        |   {
deploy-web-1        |     "code": "invalid_type",
deploy-web-1        |     "expected": "string",
deploy-web-1        |     "received": "undefined",
deploy-web-1        |     "path": [
deploy-web-1        |       "BASE_API_SANDBOX_URL"
deploy-web-1        |     ],
deploy-web-1        |     "message": "Required"
deploy-web-1        |   },
deploy-web-1        |   {
deploy-web-1        |     "code": "invalid_type",
deploy-web-1        |     "expected": "string",
deploy-web-1        |     "received": "undefined",
deploy-web-1        |     "path": [
deploy-web-1        |       "GITHUB_CLIENT_SECRET"
deploy-web-1        |     ],
deploy-web-1        |     "message": "Required"
deploy-web-1        |   },
deploy-web-1        |   {
deploy-web-1        |     "code": "invalid_type",
deploy-web-1        |     "expected": "string",
deploy-web-1        |     "received": "undefined",
deploy-web-1        |     "path": [
deploy-web-1        |       "BITBUCKET_CLIENT_SECRET"
deploy-web-1        |     ],
deploy-web-1        |     "message": "Required"
deploy-web-1        |   },
deploy-web-1        |   {
deploy-web-1        |     "code": "invalid_type",
deploy-web-1        |     "expected": "string",
deploy-web-1        |     "received": "undefined",
deploy-web-1        |     "path": [
deploy-web-1        |       "GITLAB_CLIENT_SECRET"
deploy-web-1        |     ],
deploy-web-1        |     "message": "Required"
deploy-web-1        |   }
deploy-web-1        | ]

at get error [as error] (webpack-internal:///(instrument)/../../node_modules/zod/lib/index.mjs:699:31)
deploy-web-1        |     at ZodObject.parse (webpack-internal:///(instrument)/../../node_modules/zod/lib/index.mjs:804:22)
deploy-web-1        |     at Module.register (webpack-internal:///(instrument)/./src/instrumentation.ts:14:29)
deploy-web-1        |     at async DevServer.runInstrumentationHookIfAvailable (/app/node_modules/next/dist/server/dev/next-dev-server.js:437:17)
deploy-web-1        |     at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:154:20)
deploy-web-1        |     at async DevServer.prepareImpl (/app/node_modules/next/dist/server/dev/next-dev-server.js:214:9)
deploy-web-1        |     at async NextServer.prepare (/app/node_modules/next/dist/server/next.js:161:13)
deploy-web-1        |     at async initializeImpl (/app/node_modules/next/dist/server/lib/render-server.js:98:5)
deploy-web-1        |     at async initialize (/app/node_modules/next/dist/server/lib/router-server.js:420:22)
deploy-web-1        |     at async Server.<anonymous> (/app/node_modules/next/dist/server/lib/start-server.js:249:36) {
deploy-web-1        |   issues: [
deploy-web-1        |     {
deploy-web-1        |       code: 'invalid_type',
deploy-web-1        |       expected: 'string',
deploy-web-1        |       received: 'undefined',
deploy-web-1        |       path: [Array],
deploy-web-1        |       message: 'Required'
deploy-web-1        |     },
deploy-web-1        |     {
deploy-web-1        |       code: 'invalid_type',
deploy-web-1        |       expected: 'string',
deploy-web-1        |       received: 'undefined',
deploy-web-1        |       path: [Array],
deploy-web-1        |       message: 'Required'
deploy-web-1        |     },
deploy-web-1        |     {
deploy-web-1        |       code: 'invalid_type',
deploy-web-1        |       expected: 'string',
deploy-web-1        |       received: 'undefined',
deploy-web-1        |       path: [Array],
deploy-web-1        |       message: 'Required'
deploy-web-1        |     },
deploy-web-1        |     {
deploy-web-1        |       code: 'invalid_type',
deploy-web-1        |       expected: 'string',
deploy-web-1        |       received: 'undefined',
deploy-web-1        |       path: [Array],
deploy-web-1        |       message: 'Required'
deploy-web-1        |     },
deploy-web-1        |     {
deploy-web-1        |       code: 'invalid_type',
deploy-web-1        |       expected: 'string',
deploy-web-1        |       received: 'undefined',
deploy-web-1        |       path: [Array],
deploy-web-1        |       message: 'Required'
deploy-web-1        |     },
deploy-web-1        |     {
deploy-web-1        |       code: 'invalid_type',
deploy-web-1        |       expected: 'string',
deploy-web-1        |       received: 'undefined',
deploy-web-1        |       path: [Array],
deploy-web-1        |       message: 'Required'
deploy-web-1        |     },
deploy-web-1        |     {
deploy-web-1        |       code: 'invalid_type',
deploy-web-1        |       expected: 'string',
deploy-web-1        |       received: 'undefined',
deploy-web-1        |       path: [Array],
deploy-web-1        |       message: 'Required'
deploy-web-1        |     },
deploy-web-1        |     {
deploy-web-1        |       code: 'invalid_type',
deploy-web-1        |       expected: 'string',
deploy-web-1        |       received: 'undefined',
deploy-web-1        |       path: [Array],
deploy-web-1        |       message: 'Required'
deploy-web-1        |     },
deploy-web-1        |     {
deploy-web-1        |       code: 'invalid_type',
deploy-web-1        |       expected: 'string',
deploy-web-1        |       received: 'undefined',
deploy-web-1        |       path: [Array],
deploy-web-1        |       message: 'Required'
deploy-web-1        |     },
deploy-web-1        |     {
deploy-web-1        |       code: 'invalid_type',
deploy-web-1        |       expected: 'string',
deploy-web-1        |       received: 'undefined',
deploy-web-1        |       path: [Array],
deploy-web-1        |       message: 'Required'
deploy-web-1        |     },

**Comment by ygrishajev** [comment]
hey @asayadi thanks for drawing our attention to this. Check out a related pr to see if it helps pls
